version: '3'

services:
  app:
    build: .
    volumes:
      - .:/go/src
    ports:
      - "3000:3000"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=meetupgo
      - MYSQL_ROOT_PASSWORD=root